#Name: Nazmul Haque Turja (Aggie ID: 800779609)
#Date: 01/19/2022
#Lab: Compilers and Automata
#Purpose: To automate the running lex files


all: lab3

lab3: symtable-removelabel.c
	gcc -o lab3 symtable-removelabel.c
run: lab3
	./lab3
clean:
	rm -f lab3